export const mockBooks = [
  {
    id: "1",
    title: "Atomic Habits",
    author: "James Clear",
    coverColor: "bg-amber-100 dark:bg-amber-900/30",
    progress: 64,
    totalPages: 320,
    currentPage: 205,
    status: "reading",
    lastOpened: "2025-06-28T10:30:00Z",
    format: "pdf",
    estimatedTimeLeft: "12 hrs",
  },
  {
    id: "2",
    title: "Deep Work",
    author: "Cal Newport",
    coverColor: "bg-blue-100 dark:bg-blue-900/30",
    progress: 18,
    totalPages: 296,
    currentPage: 53,
    status: "reading",
    lastOpened: "2025-06-27T14:20:00Z",
    format: "epub",
    estimatedTimeLeft: "24 hrs",
  },
  {
    id: "3",
    title: "The Psychology of Money",
    author: "Morgan Housel",
    coverColor: "bg-green-100 dark:bg-green-900/30",
    progress: 82,
    totalPages: 256,
    currentPage: 210,
    status: "reading",
    lastOpened: "2025-06-28T08:15:00Z",
    format: "pdf",
    estimatedTimeLeft: "3 hrs",
  },
  {
    id: "4",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    coverColor: "bg-purple-100 dark:bg-purple-900/30",
    progress: 0,
    totalPages: 499,
    currentPage: 0,
    status: "want_to_read",
    lastOpened: null,
    format: "pdf",
    estimatedTimeLeft: "38 hrs",
  },
  {
    id: "5",
    title: "Meditations",
    author: "Marcus Aurelius",
    coverColor: "bg-stone-100 dark:bg-stone-900/30",
    progress: 100,
    totalPages: 256,
    currentPage: 256,
    status: "finished",
    lastOpened: "2025-03-12T16:45:00Z",
    format: "epub",
    estimatedTimeLeft: "0 hrs",
  },
  {
    id: "6",
    title: "The Structure of Scientific Revolutions",
    author: "Thomas S. Kuhn",
    coverColor: "bg-rose-100 dark:bg-rose-900/30",
    progress: 45,
    totalPages: 218,
    currentPage: 98,
    status: "reading",
    lastOpened: "2025-06-26T11:00:00Z",
    format: "pdf",
    estimatedTimeLeft: "8 hrs",
  },
];

export const mockVocabulary = [
  {
    id: "1",
    word: "Meticulous",
    partOfSpeech: "Adjective",
    mastery: "B2",
    masteryLevel: 65,
    meaning: "Showing great attention to detail; very careful and precise.",
    pronunciation: "/məˈtɪkjələs/",
    example: "She is meticulous when writing code, ensuring every function is perfectly optimized.",
    synonyms: ["thorough", "careful", "precise", "scrupulous"],
    antonyms: ["careless", "sloppy", "negligent"],
    etymology: "From Latin meticulosus (fearful), from metus (fear). The meaning shifted from fearful to careful precision.",
    nextReview: "2025-06-30T10:00:00Z",
    tags: ["adjective", "B2"],
    dateAdded: "2025-06-15T10:00:00Z",
  },
  {
    id: "2",
    word: "Stoic",
    partOfSpeech: "Adjective",
    mastery: "C1",
    masteryLevel: 80,
    meaning: "Enduring pain and hardship without showing feelings or complaining.",
    pronunciation: "/ˈstoʊɪk/",
    example: "He remained stoic throughout the ordeal, never once complaining about the difficulty.",
    synonyms: ["unemotional", "impassive", "phlegmatic", "resigned"],
    antonyms: ["emotional", "expressive", "passionate"],
    etymology: "From Greek stoikos, relating to the Stoic philosophers who advocated for emotional restraint.",
    nextReview: "2025-07-02T10:00:00Z",
    tags: ["adjective", "C1"],
    dateAdded: "2025-06-10T10:00:00Z",
  },
  {
    id: "3",
    word: "Abstruse",
    partOfSpeech: "Adjective",
    mastery: "C2",
    masteryLevel: 40,
    meaning: "Difficult to understand; obscure and complex.",
    pronunciation: "/əbˈstruːs/",
    example: "The professor's abstruse lecture left most students confused about the fundamental concepts.",
    synonyms: ["obscure", "esoteric", "recondite", "cryptic"],
    antonyms: ["clear", "simple", "obvious"],
    etymology: "From Latin abstrusus, meaning hidden or concealed, from abstrudere (to conceal).",
    nextReview: "2025-06-29T10:00:00Z",
    tags: ["adjective", "C2"],
    dateAdded: "2025-06-20T10:00:00Z",
  },
  {
    id: "4",
    word: "Ephemeral",
    partOfSpeech: "Adjective",
    mastery: "B2",
    masteryLevel: 55,
    meaning: "Lasting for a very short time; transitory.",
    pronunciation: "/ɪˈfemərəl/",
    example: "The ephemeral beauty of cherry blossoms makes them all the more precious.",
    synonyms: ["fleeting", "transient", "momentary", "brief"],
    antonyms: ["permanent", "enduring", "eternal"],
    etymology: "From Greek ephēmeros, lasting only a day, from epi (on) + hēmera (day).",
    nextReview: "2025-07-01T10:00:00Z",
    tags: ["adjective", "B2"],
    dateAdded: "2025-06-18T10:00:00Z",
  },
  {
    id: "5",
    word: "Pragmatic",
    partOfSpeech: "Adjective",
    mastery: "B2",
    masteryLevel: 90,
    meaning: "Dealing with things sensibly and realistically in a way that is based on practical rather than theoretical considerations.",
    pronunciation: "/præɡˈmætɪk/",
    example: "We need a pragmatic approach to solve this engineering problem.",
    synonyms: ["practical", "realistic", "sensible", "matter-of-fact"],
    antonyms: ["idealistic", "impractical", "theoretical"],
    etymology: "From Greek pragmatikos, relating to business or action, from pragma (deed).",
    nextReview: "2025-07-15T10:00:00Z",
    tags: ["adjective", "B2"],
    dateAdded: "2025-05-20T10:00:00Z",
  },
];

export const mockNotes = [
  {
    id: "1",
    bookId: "1",
    bookTitle: "Atomic Habits",
    text: "The aggregation of marginal gains - small improvements of 1% compound into remarkable results.",
    highlight: "highlight-yellow",
    page: 14,
    createdAt: "2025-06-28T10:30:00Z",
    updatedAt: "2025-06-28T10:30:00Z",
    color: "#fde047",
  },
  {
    id: "2",
    bookId: "1",
    bookTitle: "Atomic Habits",
    text: "Habits are the compound interest of self-improvement.",
    highlight: "highlight-blue",
    page: 22,
    createdAt: "2025-06-27T14:20:00Z",
    updatedAt: "2025-06-27T14:20:00Z",
    color: "#93c5fd",
  },
  {
    id: "3",
    bookId: "2",
    bookTitle: "Deep Work",
    text: "Deep work is the ability to focus without distraction on a cognitively demanding task.",
    highlight: "highlight-green",
    page: 32,
    createdAt: "2025-06-26T11:00:00Z",
    updatedAt: "2025-06-26T11:00:00Z",
    color: "#86efac",
  },
];

export const mockAnalytics = {
  totalBooks: 6,
  booksRead: 1,
  totalPagesRead: 566,
  totalWordsLearned: 124,
  readingStreak: 12,
  averageReadingTime: 45,
  weeklyReading: [
    { day: "Mon", minutes: 60 },
    { day: "Tue", minutes: 45 },
    { day: "Wed", minutes: 30 },
    { day: "Thu", minutes: 75 },
    { day: "Fri", minutes: 50 },
    { day: "Sat", minutes: 90 },
    { day: "Sun", minutes: 40 },
  ],
  monthlyProgress: [
    { month: "Jan", pages: 120 },
    { month: "Feb", pages: 180 },
    { month: "Mar", pages: 240 },
    { month: "Apr", pages: 200 },
    { month: "May", pages: 310 },
    { month: "Jun", pages: 280 },
  ],
};

export const mockDictionary = {
  meticulous: {
    word: "Meticulous",
    partOfSpeech: "Adjective",
    pronunciation: "/məˈtɪkjələs/",
    meaning: "Showing great attention to detail; very careful and precise.",
    difficulty: "B2",
    examples: [
      "She is meticulous when writing code.",
      "The report was prepared with meticulous attention to detail.",
      "He took meticulous notes during the lecture.",
    ],
    synonyms: ["thorough", "careful", "precise", "scrupulous", "rigorous"],
    antonyms: ["careless", "sloppy", "negligent", "haphazard"],
  },
  stoic: {
    word: "Stoic",
    partOfSpeech: "Adjective / Noun",
    pronunciation: "/ˈstoʊɪk/",
    meaning: "Enduring pain and hardship without showing feelings or complaining.",
    difficulty: "C1",
    examples: [
      "He remained stoic throughout the challenge.",
      "The stoic philosopher accepted fate with equanimity.",
    ],
    synonyms: ["unemotional", "impassive", "phlegmatic", "resigned"],
    antonyms: ["emotional", "expressive", "passionate", "sentimental"],
  },
  ephemeral: {
    word: "Ephemeral",
    partOfSpeech: "Adjective",
    pronunciation: "/ɪˈfemərəl/",
    meaning: "Lasting for a very short time; transitory.",
    difficulty: "B2",
    examples: [
      "The ephemeral beauty of cherry blossoms makes them precious.",
      "Social media fame is often ephemeral.",
    ],
    synonyms: ["fleeting", "transient", "momentary", "brief"],
    antonyms: ["permanent", "enduring", "eternal", "lasting"],
  },
};

export const aiResponses = {
  explain: "This text discusses the concept of marginal gains — the idea that small, incremental improvements (just 1% better each day) compound over time to produce remarkable results. The key insight is that habits multiply rather than add, similar to compound interest in finance.",
  explainSimple: "Imagine getting just a tiny bit better every day. After one year, you'd be 37 times better! That's what this text means. It's like saving a penny every day — it adds up to a lot over time.",
  summarize: "The passage introduces the concept of atomic habits — small changes that compound into significant outcomes. It uses the metaphor of compound interest to explain how 1% daily improvements lead to transformative results over time.",
  examples: [
    "Reading 10 pages a day = 3,650 pages a year (about 12 books)",
    "Writing 200 words daily = 73,000 words annually (a full novel)",
    "Practicing guitar for 15 minutes daily = 91 hours per year",
  ],
};
